### ISSUE TITLE
Błąd przy zakłądaniu joba w ccdphotsvc

### ISSUE THREAD

**Issue by arturkrawczyk** [BHTOM-Team/bhtom#157]
Traceback (most recent call last):
  File "/home/observer/ccdphotsvc/venv/lib64/python3.6/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/observer/ccdphotsvc/venv/lib64/python3.6/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/observer/ccdphotsvc/venv/lib64/python3.6/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/observer/ccdphotsvc/venv/lib64/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x2b84ca2b8160>}
Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "/home/observer/ccdphotsvc/venv/lib64/python3.6/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/observer/ccdphotsvc/venv/lib64/python3.6/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/observer/ccdphotsvc/venv/lib64/python3.6/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/observer/ccdphotsvc/venv/lib64/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x2b84ca2b8160>}

**Comment by majkelx** [comment]
OK, załóżmy że ten błąd dotyczy tego zgłoszenia:

![image (3)](https://user-images.githubusercontent.com/8569721/226368851-d223a8c2-ff8f-47fb-bed3-8a4311a4620e.png)

**Comment by majkelx** [comment]
@arturkrawczyk namierzył:
![image (4)](https://user-images.githubusercontent.com/8569721/226373562-e57ad51a-db56-424c-982c-7b8be60ced32.png)

**Comment by astromiki** [comment]
@majkelx @arturkrawczyk 
No więc, czy możemy wydłużyć to pole do 100 znaków? Tyle na bank wystarczy.
Jeśli jednak pojawi się błąd, to niech komunikat brzmi: CCDPHOTD 400 error: observatory name too long.

**Comment by majkelx** [comment]
Pewnie błąd mógłby brzmieć `instrument: Ensure this field has no more than 50 characters` (bo taki komunikat idzie z `ccdphotsvc`)

**Comment by majkelx** [comment]
@astromiki jakieś inne pola zmienić?
